version: '3.2'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    hostname: kafka
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
      #This is set to your local ip address, this is messy
      - KAFKA_ADVERTISED_HOST_NAME=192.168.1.244
      - KAFKA_CREATE_TOPICS= "test-0:1:1,test-1:1:1"
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

  remora:
    image: registry.opensource.zalan.do/machina/remora
    depends_on:
      - kafka
    links:
      - kafka
    environment:
      - KAFKA_ENDPOINT=kafka:9092
#      JAVA_OPTS:
#        -Xmx1g
#        -Dcom.sun.management.jmxremote.rmi.port=9090
#        -Dcom.sun.management.jmxremote=true
#        -Dcom.sun.management.jmxremote.port=9090
#        -Dcom.sun.management.jmxremote.ssl=false
#        -Dcom.sun.management.jmxremote.authenticate=false
#        -Dcom.sun.management.jmxremote.local.only=false
#        -Djava.rmi.server.hostname=localhost
    ports:
      - 9000:9000


  cassandra0:
    image: cassandra:3.11
    container_name: cassandra0
    ports:
      - 9042:9042
      - 9160:9160
      - 7199:7199
      - 8778:8778
    environment:
      - CASSANDRA_START_RPC=true


  cassandra-node-1:
    image: cassandra:3.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=seed"
    links:
      - cassandra0:seed
    depends_on:
      - "cassandra0"

  # you cannot have multiple nodes join the cluster at the same time when
  # cassandra.consistent.rangemovement is true so we further delay it to give it time to stabilize
#  cassandra-node-2:
#    image: cassandra:3.11
#    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 80 && /docker-entrypoint.sh cassandra -f"
#    environment:
#      - "CASSANDRA_SEEDS=seed"
#    links:
#     - cassandra0:seed
#    depends_on:
#     - "cassandra0"

##############################
  grafana:
    image: grafana/grafana:master
    container_name: grafana
    environment:
      - DS_NAME=kairosdb
      - DS_TYPE=kairosdb
      - DS_ACCESS=proxy
      - DS_URL=http://kairosdb:8083
      - DS_IS_DEFAULT=true
      - DS_AUTH=false
    links:
      - kairosdb
    ports:
      - 3000:3000

  kairosdb:
    image: wangdrew/kairosdb
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 60 && /usr/bin/config-kairos.sh"
    container_name: kairosdb
    environment:
      - CASSANDRA_HOST_LIST=cassandra0:9160
    ports:
      - "4242:4242"
      - "8083:8083"
    links:
      - cassandra0
    depends_on:
      - cassandra-node-1


#
#Build example
#kairosdb:
#  build: apps/kairosdb
#  command: /bin/bash -c "/opt/kairosdb/bin/kairosdb.sh run"
#  restart: always
#  ports:
#    - "4242:4242"
#    - "8080:8080"
#links: